apiVersion: v1
kind: ConfigMap
metadata:
  name: opencargo-config
  labels:
    app: opencargo
data:
  config.toml: |
    [server]
    bind = "0.0.0.0:6789"
    base_url = "http://localhost:6789"
    storage_path = "/data/storage"

    [database]
    url = "sqlite:/data/db/opencargo.db?mode=rwc"

    [auth]
    anonymous_read = true
