apiVersion: v1
kind: Service
metadata:
  name: opencargo
  labels:
    app: opencargo
spec:
  type: ClusterIP
  ports:
    - port: 6789
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: opencargo
