apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-opencargo-config
  labels:
    app: opencargo
    release: {{ .Release.Name }}
data:
  config.toml: |
{{ .Values.config | indent 4 }}
