apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-opencargo-secret
  labels:
    app: opencargo
    release: {{ .Release.Name }}
type: Opaque
data:
  admin-password: {{ .Values.auth.adminPassword | b64enc | quote }}
