-- The schema of a database that ran 001-012 and nothing since: the shape that
-- predates the version table and that the baseline must probe rather than
-- assume. Generated by applying 001-012 to an empty file and dumping
-- sqlite_master in creation order, minus the objects SQLite owns
-- (`sqlite_sequence`, the autoindexes and the fts5 shadow tables), which the
-- statements below recreate on their own. Never copied from a live database.
CREATE TABLE repositories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    repo_type TEXT NOT NULL CHECK(repo_type IN ('hosted', 'proxy', 'group')),
    format TEXT NOT NULL CHECK(format IN ('npm', 'cargo', 'oci', 'go', 'pypi')),
    visibility TEXT NOT NULL DEFAULT 'private' CHECK(visibility IN ('public', 'private')),
    upstream_url TEXT,
    config_json TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE packages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    repository_id INTEGER NOT NULL REFERENCES repositories(id),
    name TEXT NOT NULL,
    description TEXT,
    readme TEXT,
    license TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(repository_id, name)
);
CREATE TABLE versions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    package_id INTEGER NOT NULL REFERENCES packages(id),
    version TEXT NOT NULL,
    metadata_json TEXT NOT NULL,
    checksum_sha1 TEXT,
    checksum_sha256 TEXT,
    integrity TEXT,
    size INTEGER NOT NULL DEFAULT 0,
    tarball_path TEXT NOT NULL,
    published_at TEXT NOT NULL DEFAULT (datetime('now')), yanked INTEGER NOT NULL DEFAULT 0,
    UNIQUE(package_id, version)
);
CREATE TABLE dist_tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    package_id INTEGER NOT NULL REFERENCES packages(id),
    tag TEXT NOT NULL,
    version_id INTEGER NOT NULL REFERENCES versions(id),
    UNIQUE(package_id, tag)
);
CREATE TABLE downloads (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    version_id INTEGER NOT NULL REFERENCES versions(id),
    downloaded_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_packages_name ON packages(name);
CREATE INDEX idx_versions_package ON versions(package_id);
CREATE INDEX idx_dist_tags_package ON dist_tags(package_id);
CREATE INDEX idx_downloads_version ON downloads(version_id);
CREATE TABLE proxy_cache_meta (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    repository_id INTEGER NOT NULL REFERENCES repositories(id),
    cache_key TEXT NOT NULL,
    fetched_at TEXT NOT NULL DEFAULT (datetime('now')),
    ttl_seconds INTEGER NOT NULL DEFAULT 86400,
    UNIQUE(repository_id, cache_key)
);
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    email TEXT,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'reader' CHECK(role IN ('admin', 'publisher', 'reader')),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
, must_change_password INTEGER NOT NULL DEFAULT 0);
CREATE TABLE api_tokens (
    id TEXT PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    prefix TEXT NOT NULL,
    token_hash TEXT NOT NULL,
    permissions_json TEXT,
    expires_at TEXT,
    last_used_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE audit_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER REFERENCES users(id),
    username TEXT,
    action TEXT NOT NULL,
    target TEXT,
    repository TEXT,
    ip TEXT,
    user_agent TEXT,
    details_json TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_api_tokens_user ON api_tokens(user_id);
CREATE INDEX idx_api_tokens_prefix ON api_tokens(prefix);
CREATE INDEX idx_audit_log_user ON audit_log(user_id);
CREATE INDEX idx_audit_log_created ON audit_log(created_at);
CREATE TABLE oci_blobs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    repository_id INTEGER NOT NULL REFERENCES repositories(id),
    digest TEXT NOT NULL,
    size INTEGER NOT NULL,
    content_type TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(repository_id, digest)
);
CREATE TABLE oci_manifests (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    repository_id INTEGER NOT NULL REFERENCES repositories(id),
    name TEXT NOT NULL,
    digest TEXT NOT NULL,
    content_type TEXT NOT NULL,
    size INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(repository_id, name, digest)
);
CREATE TABLE oci_tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    repository_id INTEGER NOT NULL REFERENCES repositories(id),
    name TEXT NOT NULL,
    tag TEXT NOT NULL,
    manifest_digest TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(repository_id, name, tag)
);
CREATE TABLE oci_uploads (
    id TEXT PRIMARY KEY,
    repository_id INTEGER NOT NULL REFERENCES repositories(id),
    name TEXT NOT NULL,
    started_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE VIRTUAL TABLE packages_fts USING fts5(
    name,
    description,
    content=packages,
    content_rowid=id
);
CREATE TRIGGER packages_fts_insert AFTER INSERT ON packages BEGIN
    INSERT INTO packages_fts(rowid, name, description) VALUES (new.id, new.name, new.description);
END;
CREATE TRIGGER packages_fts_delete AFTER DELETE ON packages BEGIN
    INSERT INTO packages_fts(packages_fts, rowid, name, description) VALUES('delete', old.id, old.name, old.description);
END;
CREATE TRIGGER packages_fts_update AFTER UPDATE ON packages BEGIN
    INSERT INTO packages_fts(packages_fts, rowid, name, description) VALUES('delete', old.id, old.name, old.description);
    INSERT INTO packages_fts(rowid, name, description) VALUES (new.id, new.name, new.description);
END;
CREATE TABLE package_dependencies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    package_id INTEGER NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
    version_id INTEGER NOT NULL REFERENCES versions(id) ON DELETE CASCADE,
    dependency_name TEXT NOT NULL,
    dependency_version_req TEXT NOT NULL,
    dependency_type TEXT NOT NULL DEFAULT 'runtime',
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_package_deps_package ON package_dependencies(package_id);
CREATE INDEX idx_package_deps_dep_name ON package_dependencies(dependency_name);
CREATE INDEX idx_package_deps_version ON package_dependencies(version_id);
CREATE TABLE vulnerability_scans (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    version_id INTEGER NOT NULL REFERENCES versions(id) ON DELETE CASCADE,
    scanned_at TEXT NOT NULL DEFAULT (datetime('now')),
    total_deps INTEGER NOT NULL DEFAULT 0,
    vulnerable_deps INTEGER NOT NULL DEFAULT 0,
    scan_results_json TEXT,
    status TEXT NOT NULL DEFAULT 'clean' CHECK(status IN ('clean', 'warning', 'critical'))
);
CREATE INDEX idx_vuln_scans_version ON vulnerability_scans(version_id);
CREATE TABLE user_permissions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    repository_id INTEGER NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    can_read INTEGER NOT NULL DEFAULT 1,
    can_write INTEGER NOT NULL DEFAULT 0,
    can_delete INTEGER NOT NULL DEFAULT 0,
    can_admin INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(user_id, repository_id)
);
CREATE INDEX idx_user_permissions_user ON user_permissions(user_id);
CREATE INDEX idx_user_permissions_repo ON user_permissions(repository_id);
CREATE TABLE webhooks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    url TEXT NOT NULL,
    events TEXT NOT NULL DEFAULT '*',
    secret TEXT,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE download_counts (
    version_id INTEGER PRIMARY KEY REFERENCES versions(id),
    count INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE oci_manifest_blobs (
    repository_id INTEGER NOT NULL REFERENCES repositories(id),
    manifest_digest TEXT NOT NULL,
    blob_digest TEXT NOT NULL,
    UNIQUE(repository_id, manifest_digest, blob_digest)
);
CREATE INDEX idx_oci_manifest_blobs_blob
    ON oci_manifest_blobs(repository_id, blob_digest);
